name: Deploy to Heroku

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Login to Heroku
        run: heroku login -i

      - name: Deploy to Heroku
        run: git push heroku HEAD:main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
